"""
Headphone Hook — Parametric Desk-Clamp Design (build123d)

A parametric desk-edge clamp with a headphone hook arm and integrated cable-wrap post.
The clamp adjusts to desk thicknesses of 12–40mm. All key dimensions are exposed as
constants at the top — adjust after first test print.

Three print profiles generated by default:
  - thin_desk  — 12mm desk thickness (typical IKEA desk tops)
  - standard   — 25mm desk thickness (most home/office desks)
  - thick_desk — 40mm desk thickness (standing desks, thick worktops)

Usage:
    python headphone_hooks.py --output-dir ./stl/
    python headphone_hooks.py --desk-thickness 20 --output-dir ./stl/
    python headphone_hooks.py --desk-thickness 12 25 40 --output-dir ./stl/
    python headphone_hooks.py --cable-post false --output-dir ./stl/
    python headphone_hooks.py --tolerance 0.3 --output-dir ./stl/

Design notes:
  - Print orientation: clamp body flat side down, hook arm pointing up
  - No supports required (hook arm angle ≤ 45° overhang)
  - Recommended slicer settings: 0.20mm layer height, 25% infill, 3 perimeters
  - Material: PLA+ (default), PETG for workshop environments
  - Estimated print time: 22–28 min per hook at 0.20mm / 25% infill on Bambu P1S
  - Estimated weight: 22–28g per hook depending on desk_thickness variant

Geometry coordinate system (all dimensions in mm):
  - X: left-right across clamp body width
  - Y: front-back (positive = toward desk front edge)
  - Z: vertical (positive = up)
  - Origin: center of back plate at mid-height of total clamp body
"""

import argparse
import os
from typing import Tuple

from build123d import *

# ============================================================
# Clamp body constants
# ============================================================

# Desk clamp geometry
CLAMP_BODY_WIDTH = 38.0        # mm — left-to-right width of clamp body
CLAMP_BODY_DEPTH = 28.0        # mm — front-to-back depth of clamp body
CLAMP_WALL_THICKNESS = 3.0     # mm — wall thickness; 3mm min for PLA+ at 25% infill
CLAMP_ARM_THICKNESS = 4.0      # mm — upper and lower jaw arm thickness
CLAMP_LOWER_OVERHANG = 22.0    # mm — how far lower jaw extends under the desk
FDM_TOLERANCE = 0.20           # mm — clearance added to jaw gap for printer tolerance

# ============================================================
# Hook arm constants
# ============================================================

HOOK_ARM_LENGTH = 55.0         # mm — horizontal reach of hook arm from clamp body
HOOK_ARM_WIDTH = 20.0          # mm — left-to-right width of hook arm
HOOK_ARM_THICKNESS = 4.0       # mm — vertical thickness of hook arm
HOOK_ARM_ANGLE = 8.0           # degrees — slight upward angle to prevent headphone sliding off
HOOK_TIP_RADIUS = 6.0          # mm — rounded tip radius (prevents cable damage)
HOOK_ATTACHMENT_HEIGHT = 25.0  # mm — Z height of hook arm above top of desk

# ============================================================
# Cable-wrap post constants
# ============================================================

CABLE_POST_ENABLED = True      # Set False to omit cable-wrap post
CABLE_POST_HEIGHT = 30.0       # mm — post height above hook arm
CABLE_POST_DIAMETER = 8.0      # mm — post diameter; sized for 4–8mm cables
CABLE_POST_OFFSET_X = 15.0     # mm — offset from hook arm centerline toward clamp

# ============================================================
# Rubber pad pocket (desk protection)
# ============================================================

PAD_POCKET_LENGTH = 20.0       # mm — pocket length along jaw
PAD_POCKET_WIDTH = 8.0         # mm — pocket width
PAD_POCKET_DEPTH = 1.5         # mm — recess depth for 1.5mm rubber pad or tape
# Rubber pad: 3M Bumpon SJ5302 or equivalent self-adhesive silicone feet, cut to size


def make_clamp_body(desk_thickness: float) -> Tuple[Solid, float]:
    """
    C-shaped clamp body that grips the desk edge.

    The C-profile consists of:
      - Vertical back plate (full height)
      - Upper jaw extending forward from top of back plate
      - Lower jaw extending forward from bottom of back plate
    The gap between upper and lower jaw = desk_thickness + FDM_TOLERANCE (each side).
    """
    jaw_gap = desk_thickness + FDM_TOLERANCE * 2  # clearance for press-fit over desk
    total_height = jaw_gap + CLAMP_ARM_THICKNESS * 2

    # Back plate — full height, depth = CLAMP_BODY_DEPTH, width = CLAMP_BODY_WIDTH
    back_plate = Box(CLAMP_BODY_WIDTH, CLAMP_WALL_THICKNESS, total_height)

    # Upper jaw — extends forward from top of back plate
    upper_jaw = Pos(
        0,
        (CLAMP_WALL_THICKNESS / 2) + (CLAMP_BODY_DEPTH / 2),
        (total_height / 2) - (CLAMP_ARM_THICKNESS / 2),
    ) * Box(CLAMP_BODY_WIDTH, CLAMP_BODY_DEPTH, CLAMP_ARM_THICKNESS)

    # Lower jaw — extends forward from bottom of back plate
    lower_jaw = Pos(
        0,
        (CLAMP_WALL_THICKNESS / 2) + (CLAMP_LOWER_OVERHANG / 2),
        -(total_height / 2) + (CLAMP_ARM_THICKNESS / 2),
    ) * Box(CLAMP_BODY_WIDTH, CLAMP_LOWER_OVERHANG, CLAMP_ARM_THICKNESS)

    # Rubber pad pocket on underside of upper jaw (desk-contact surface)
    pad_pocket = Pos(
        0,
        (CLAMP_WALL_THICKNESS / 2) + (CLAMP_BODY_DEPTH / 2),
        (total_height / 2) - CLAMP_ARM_THICKNESS + (PAD_POCKET_DEPTH / 2),
    ) * Box(PAD_POCKET_LENGTH, PAD_POCKET_WIDTH, PAD_POCKET_DEPTH)
    upper_jaw -= pad_pocket

    # Rubber pad pocket on topside of lower jaw (desk-contact surface)
    lower_pad_pocket = Pos(
        0,
        (CLAMP_WALL_THICKNESS / 2) + (CLAMP_LOWER_OVERHANG / 2),
        -(total_height / 2) + CLAMP_ARM_THICKNESS - (PAD_POCKET_DEPTH / 2),
    ) * Box(PAD_POCKET_LENGTH, PAD_POCKET_WIDTH, PAD_POCKET_DEPTH)
    lower_jaw -= lower_pad_pocket

    clamp = back_plate + upper_jaw + lower_jaw
    return clamp, total_height


def make_hook_arm() -> Solid:
    """
    Headphone hook arm that extends from the upper portion of the clamp body.

    The arm is positioned at HOOK_ATTACHMENT_HEIGHT above desk surface (top of upper jaw).
    It is angled slightly upward at HOOK_ARM_ANGLE degrees to prevent headphones from
    sliding off under their own weight.

    The tip is rounded with HOOK_TIP_RADIUS to prevent cable kinking and headphone
    headband damage.

    Returns the arm solid, positioned relative to the clamp body origin.
    All vertical positioning uses HOOK_ATTACHMENT_HEIGHT (module-level constant).
    """
    import math

    # Main arm: rectangular extrusion from clamp body forward
    # Horizontal portion first, then rotate to introduce the angle
    arm_length_adjusted = HOOK_ARM_LENGTH / math.cos(math.radians(HOOK_ARM_ANGLE))
    arm = Box(HOOK_ARM_WIDTH, arm_length_adjusted, HOOK_ARM_THICKNESS)

    # Round the tip of the hook arm (free end at +Y face)
    try:
        # Select edges at the free end (+Y face, all Z edges)
        tip_edges = arm.edges().filter_by_position(
            Axis.Y,
            arm_length_adjusted / 2 - 0.1,
            arm_length_adjusted / 2 + 0.1,
        )
        arm = fillet(tip_edges, radius=HOOK_TIP_RADIUS)
    except Exception:
        pass  # cosmetic — skip if edge selection fails

    # Apply upward angle by rotating around X axis (tip tilts up)
    arm = Rot(X=-HOOK_ARM_ANGLE) * arm

    # Position arm at the correct height: HOOK_ATTACHMENT_HEIGHT above top jaw
    # The arm attaches to the front face of the clamp body
    arm = Pos(0, CLAMP_BODY_DEPTH / 2 + arm_length_adjusted / 2, HOOK_ATTACHMENT_HEIGHT) * arm

    return arm


def make_cable_post() -> Solid:
    """
    Vertical cable-wrap post rising from the hook arm base.

    The post sits at CABLE_POST_OFFSET_X from the hook arm centerline, offset toward
    the clamp body. Cables are looped around the post to prevent slack accumulation.
    Post diameter sized for 4–8mm cables with comfortable finger clearance.
    """
    post = Cylinder(CABLE_POST_DIAMETER / 2, CABLE_POST_HEIGHT)

    # Rounded top on the post (prevents cable abrasion)
    try:
        top_edges = post.edges().filter_by_position(
            Axis.Z, CABLE_POST_HEIGHT / 2 - 0.1, CABLE_POST_HEIGHT / 2 + 0.1
        )
        post = fillet(top_edges, radius=CABLE_POST_DIAMETER / 4)
    except Exception:
        pass

    # Position: offset from hook arm centerline, at hook arm attachment height
    post = Pos(
        CABLE_POST_OFFSET_X,
        CLAMP_BODY_DEPTH / 2 + CABLE_POST_DIAMETER,  # just forward of clamp body
        HOOK_ATTACHMENT_HEIGHT + HOOK_ARM_THICKNESS / 2,
    ) * post

    return post


def make_hook(desk_thickness: float, include_cable_post: bool = True) -> Solid:
    """
    Assemble complete headphone hook: clamp body + hook arm + optional cable-wrap post.

    Args:
        desk_thickness: Desk top thickness in mm (12–40mm range).
        include_cable_post: If True, include the cable-wrap post.

    Returns:
        Complete hook solid ready for STL export.
    """
    clamp, _clamp_height = make_clamp_body(desk_thickness)
    arm = make_hook_arm()

    hook = clamp + arm

    if include_cable_post:
        post = make_cable_post()
        hook = hook + post

    return hook


def export_hook(
    desk_thickness: float,
    output_path: str,
    include_cable_post: bool = True,
) -> None:
    label = f"desk={desk_thickness}mm, cable_post={include_cable_post}"
    print(f"Building hook: {label} → {output_path}")
    hook = make_hook(desk_thickness, include_cable_post)
    export_stl(hook, output_path)
    print(f"  Exported: {output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Generate parametric headphone hook STL files"
    )
    parser.add_argument(
        "--desk-thickness",
        type=float,
        nargs="+",
        default=[12.0, 25.0, 40.0],
        metavar="MM",
        help="Desk thickness in mm. Repeat for multiple variants. Default: 12 25 40",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default=".",
        help="Output directory for STL files (default: .)",
    )
    parser.add_argument(
        "--cable-post",
        type=lambda x: x.lower() not in ("false", "0", "no"),
        default=True,
        metavar="BOOL",
        help="Include cable-wrap post (default: true). Pass 'false' to omit.",
    )
    parser.add_argument(
        "--tolerance",
        type=float,
        default=None,
        help=f"Override FDM jaw tolerance in mm (default {FDM_TOLERANCE}). "
             f"Increase if clamp is too tight on desk.",
    )
    args = parser.parse_args()

    if args.tolerance is not None:
        global FDM_TOLERANCE
        FDM_TOLERANCE = args.tolerance
        print(f"Using custom FDM tolerance: {args.tolerance}mm")

    os.makedirs(args.output_dir, exist_ok=True)

    for thickness in args.desk_thickness:
        cable_tag = "with_post" if args.cable_post else "no_post"
        filename = f"headphone_hook_{int(thickness)}mm_{cable_tag}.stl"
        output_path = os.path.join(args.output_dir, filename)
        export_hook(thickness, output_path, args.cable_post)

    count = len(args.desk_thickness)
    print(f"\nDone. {count} hook(s) exported to {args.output_dir}/")
    print(f"\nTuning notes:")
    print(f"  Clamp too tight on desk: increase --tolerance (now {FDM_TOLERANCE}mm)")
    print(f"  Hook arm too short: increase HOOK_ARM_LENGTH (now {HOOK_ARM_LENGTH}mm)")
    print(f"  Headphones slide off: increase HOOK_ARM_ANGLE (now {HOOK_ARM_ANGLE} deg)")
    print(f"  Cable post too thin: increase CABLE_POST_DIAMETER (now {CABLE_POST_DIAMETER}mm)")
    print(f"  Print too heavy: reduce CLAMP_BODY_DEPTH or HOOK_ARM_WIDTH")


if __name__ == "__main__":
    main()
